создание упражнения
ioreshkin/myfit-files pull request #12
Opened 2024-12-06 14:15 UTC by PavelSharko

2024-12-10 13:20 UTC, sergey-oreshkin requested changes

2024-12-10 13:20 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/ExerciseService.java
> +  public ResponseEntity<ExerciseDto> validateExercise(ExerciseDto exerciseDto, String token) {
назови метод saveExercise

2024-12-10 18:41 UTC, PavelSharko commented on src/main/java/center/myfit/controller/FileController.java
> +    log.info("Принят запрос на сохранение файла");
просто log.info("Запрос на создание упражнения {}", exerciseDto.**_**_title());_**_**
(рекорд класс)

2024-12-11 06:34 UTC, sergey-oreshkin approved these changes

2024-12-11 07:22 UTC, ioreshkin approved these changes

2024-12-11 07:41 UTC, ioreshkin approved these changes

2024-12-11 07:44 UTC, ioreshkin approved these changes

2024-12-11 07:46 UTC, merged