конвертация и отправка в бэк на сохранение
ioreshkin/myfit-files pull request #14
Opened 2024-12-19 13:03 UTC by PavelSharko

2024-12-21 13:46 UTC, sergey-oreshkin requested changes

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/facade/file/FileFacade.java
> +      MultipartFile originalFile = downloadFileService.downloadFile(originalUrl);
это лучше вынести из блока try, downloadFileService.downloadFile там кидает свое исключение и тут лишний раз его ловим и перепрокидываем

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/listener/ImageTaskListener.java
> +    log.info("принята задача из очереди {}", config.getExercise().getImage());
тут хорошо бы логировать exerciseid, чтоб понятно было потом по логам на каком изображении проблемы

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/exercise/ExerciseService.java
> +
много пустых строк

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/ConvertFileService.java
> +    log.info("старт конвертации файла по формату: {}", width, " x ", height);
не верное форматирование, плейсхолдеров должно быть столько же сколько параметров   
`log.info("старт конвертации файла по формату: {} х {}", width, height);`

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/ConvertFileService.java
> +    File tempFile = File.createTempFile("tempImage", ".jpg");
по моему такие операции могут здорово сожрать память, а уничтожаются они только после остановки JVM.   
а сервера работают месяцами без перезагрузки..   
давай переделаем все приложение на InputStream. Все методы работающие с изображениями должны принимать и возвращать InputStream. Так мы точно избежим утечек памяти..   
в том числе переделай плз и fileService.uploadFile

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/ConvertFileService.java
> +    return tempFile; // Возвращаем временный файл
вот так примерно    
```
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
Thumbnails.of(inputStream).size(width, height).toOutputStream(outputStream);
return new ByteArrayInputStream(outputStream.toByteArray());
```

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/DownloadFileService.java
> +      String objectName = parts[4];
я вообще забыл сказать что предполагается что вся наша система знает минио урл и имя бакета, так что в дто передаются только имя объекта. поэтому не надо парсить..

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/DownloadFileService.java
> +              .object(objectName)
имя бакета бери из конфига, имя объекта это originalUrl

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/DownloadFileService.java
> +  /** Загрузка файла из MinIO по URL без авторизации. */
без авторизации тут лишнее, так как minioClient как раз авторизован как надо

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/DownloadFileService.java
> +              .object(objectName)
и дальше передавай InputStream, не надо его никак преобразовывать

2024-12-21 13:46 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/utils/FileUtilsHelper.java
> +public class FileUtilsHelper {
этот класс наверно станет не нужен - не забудь удалить

2024-12-23 17:48 UTC, PavelSharko commented on src/main/java/center/myfit/config/QueueProperties.java
> +  private ExerciseSave exerciseSave;
так и сделал, просто в класс Exercise , добаввил новое поле
imageToSave(название очереди) для отрпавки на сохранение

2024-12-23 18:01 UTC, PavelSharko commented on src/main/java/center/myfit/config/SizeImageProperties.java
> +  private Desktop desktop;
убрал все в один класс

2024-12-23 18:11 UTC, PavelSharko commented on src/main/java/center/myfit/facade/file/FileFacade.java
> +      MultipartFile originalFile = downloadFileService.downloadFile(originalUrl);
согласен, убрал

2024-12-23 19:56 UTC, PavelSharko commented on src/main/java/center/myfit/listener/ImageTaskListener.java
> +    log.info("принята задача из очереди {}", config.getExercise().getImage());
добавил в параметры логирования

2024-12-23 21:53 UTC, PavelSharko commented on src/main/java/center/myfit/service/file/DownloadFileService.java
> +              .object(objectName)
везде теперь передается InputStream

2024-12-23 22:16 UTC, PavelSharko commented on src/main/java/center/myfit/controller/ExerciseController.java
> +      log.error("Ошибка при получении потока из MultipartFile", e);
стоит ли это в отловить в CommonExceptionHandler, и логи туда уйдут?

2024-12-23 22:17 UTC, PavelSharko commented on src/main/java/center/myfit/service/file/ConvertFileService.java
> +   * Конвертация изображения по заданным размерам.
нужно ли писать такой формат джав док или достаточно название метода?

2024-12-24 15:42 UTC, sergey-oreshkin commented on src/main/java/center/myfit/service/file/ConvertFileService.java
> +   * Конвертация изображения по заданным размерам.
джавадоки должны описывать как работает метод, так что лучше писать так

2024-12-24 15:51 UTC, sergey-oreshkin requested changes

2025-01-23 15:39 UTC, sergey-oreshkin approved these changes

2025-01-23 15:39 UTC, merged