Issues 1,2,3
ioreshkin/myfit-files pull request #4
Opened 2024-11-20 11:36 UTC by PavelSharko

2024-11-20 14:07 UTC, sergey-oreshkin requested changes
файл с картинкой давай уберем из репы вообще

2024-11-20 14:07 UTC, sergey-oreshkin commented on src/main/java/com/sharko/myfit/service/FileService.java
> +            System.out.println("Проверяем существование bucket: " + bucketName);
писать надо в логи. используй @Slf4j   
везде поправь плз

2024-11-20 14:07 UTC, sergey-oreshkin commented on src/main/java/com/sharko/myfit/service/FileService.java
> +            e.printStackTrace();
эксепшены логируем тоже

2024-11-20 14:07 UTC, sergey-oreshkin commented on src/main/java/com/sharko/myfit/service/FileService.java
> +            if (!isBucketExist) {
давай проверку и создание бакета вынесем в старт приложения, например в  @PostConstruct

2024-11-20 14:07 UTC, sergey-oreshkin commented on src/main/resources/application.properties
> +minio.bucket-name=minio1
давай это будем делать в yml

2024-11-20 14:08 UTC, sergey-oreshkin commented on pom.xml
> +        <relativePath/> <!-- lookup parent from repository -->
я про relativePath

2024-11-21 10:40 UTC, sergey-oreshkin requested changes

2024-11-21 10:40 UTC, sergey-oreshkin commented on .gitignore
> -# Compiled class file
его надо не удалить, а чтоб он совпадал с тем что в develop, чтоб тут разница не светилась

2024-11-21 10:40 UTC, sergey-oreshkin commented on pom.xml
> +        </dependency>
там нормальный же логгер спринговый, это пока наверное не нужно
просто юзай ломбок @Slf4j и все

2024-11-21 10:40 UTC, sergey-oreshkin commented on src/main/java/com/sharko/myfit/exeption/CustomExceptionHandler.java
> +    @ExceptionHandler
тут надо в скобках указывать для какого именно эксепшена этот хэндлер и очень желательно чтоб он совпадал с тем что принимает метод

2024-11-21 10:40 UTC, sergey-oreshkin commented on src/main/resources/application.yaml
> +  config: classpath:log4j2.xml
это вообще лучше пока убрать и использовать спринговый логгер   
в pom выпили там эти зависимости вообще   
пока нам не нужно делать что то особенное, типа отправлять логу куда то кроме консоли

2024-11-21 12:05 UTC, sergey-oreshkin requested changes

2024-11-21 12:05 UTC, sergey-oreshkin commented on src/main/java/com/sharko/myfit/MyfitFilesApplication.java
> +package com.sharko.myfit;
все пакеты должны начинаться с center.myfit

2024-11-22 05:54 UTC, sergey-oreshkin commented on src/main/java/com/sharko/myfit/exeption/CustomExceptionHandler.java
> +    }
вернее это исправь чтоб ловил Exception, ну и раз так широко ловим, то надо возвращать 500 - INTERNAL_SERVER_ERROR

2024-11-22 08:47 UTC, PavelSharko commented on .gitignore
> -# Compiled class file
скопировал из девелоп

2024-11-22 09:05 UTC, PavelSharko commented on pom.xml
> +        </dependency>
точно, странно я думал надо зависимоти эти вручную добавлять, и тогда был конфлик, приходилось делать исключение 
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.springframework.boot</groupId>-->
<!--                    <artifactId>spring-boot-starter-logging</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
        </dependency>
        
        
        все сейчас сделал что используется спринговый логер,

2024-11-22 09:05 UTC, PavelSharko commented on pom.xml
> +        </dependency>
вопрос такой, в файл надо писать логи?

2024-11-22 09:29 UTC, PavelSharko commented on src/main/java/com/sharko/myfit/exeption/CustomExceptionHandler.java
> +    @ExceptionHandler
дописал

2024-11-22 09:30 UTC, PavelSharko commented on src/main/java/com/sharko/myfit/exeption/CustomExceptionHandler.java
> +    }
поправил, теперь принимает Еxception

2024-11-22 09:32 UTC, PavelSharko commented on src/main/resources/application.yaml
> +  config: classpath:log4j2.xml
все убрал, я пока добавил файл в  проперти logback-spring.xml, там настраивается как логи хранить и где, .если не надо уберу, но в application.yaml не стал к ниму писать путь, при компиляции он автоматом подхватывает

2024-11-22 09:36 UTC, PavelSharko commented on src/main/java/com/sharko/myfit/MyfitFilesApplication.java
> +package com.sharko.myfit;
поменял структуру

2024-11-22 09:39 UTC, PavelSharko commented on HELP.md
> +
убрал ,

2024-11-22 10:50 UTC, sergey-oreshkin approved these changes

2024-11-22 10:53 UTC, merged